image: Ubuntu

test_script:
- |
  gcc --version
  cat /proc/cpuinfo | grep flags
  gcc -O0 -DNOBMI andn-asm.c
  objdump -d a.out
  ./a.out 13 3
  gcc -mbmi -O3 andn-asm.c
  objdump -d a.out
  ./a.out 13 3
  gcc -mbmi -O3 catcher.c -o catcher.out
  ./catcher.out 13 3

build: off
